apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "httpd.selectorLabels" . | nindent 4 }}
  name: {{ include "httpd.fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
    {{- include "httpd.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
    {{- include "httpd.selectorLabels" . | nindent 8 }}
      name: {{ include "httpd.fullname" . }}
    spec:
      containers:
      - env:
        - name: HTTPD_LOG_TYPE
          value: json
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: httpd
        ports:
        - containerPort: 8443
          name: httpds
        livenessProbe:
          httpGet:
            path: /
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 30
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 3
          timeoutSeconds: 3
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /var/www/html
          name: {{ include "httpd.fullname" . }}-data
#        TODO: Add extra configmaps from values
        - mountPath: /opt/httpd/tls
          name: {{ include "httpd.fullname" . }}-ssl
      {{- if .Values.monitor.enabled }}
      - image: "{{ .Values.monitor.image.repository }}:{{ .Values.monitor.image.tag }}"
        name: httpd-exporter
        ports:
        - containerPort: 9117
          name: prometheus
        args:
        - '--scrape_uri=https://localhost:8443/server-status/?auto'
        - '--log.format=json'
        - '--insecure'
      {{ end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: {{ include "httpd.fullname" . }}-data
        persistentVolumeClaim:
          claimName: {{ include "httpd.fullname" . }}-data
      - name: {{ include "httpd.fullname" . }}-ssl
        secret:
          defaultMode: 0755
          secretName: {{ include "httpd.fullname" . }}-ssl
