{{- if .Values.storage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "httpd.fullname" . }}-data
spec:
  storageClassName: {{ .Values.storage.storageClass }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{ end }}