apiVersion: v1
kind: Service
metadata:
  name: {{ include "httpd.fullname" . }}
  labels:
    {{- include "httpd.selectorLabels" . | nindent 4 }}
spec:
  ports:
  - name: web
    port: {{ .Values.service.port }}
    {{- if .Values.certManager.enabled }}
    targetPort: 8443
    {{- else }}
    targetPort: 8080
    {{- end }}
  - name: prometheus
    port: 9117
    targetPort: 9117
  selector:
    {{- include "httpd.selectorLabels" . | nindent 4 }}